server:
  port: 8080

spring:
  application:
    name: sanchay
  docker:
    compose:
      enabled: true
      file: server/compose.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/sanchay
    username: sanchay
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
